Successfull logout
AlexTelon/FlexiCharge-My-pages pull request #135
Opened 2023-09-19 11:15 UTC by GabrielAdward

# Pull Request
## Issue number
> [!Note]
> Enter what Issue you have solved.
> Put an # infront of the Issue number.

## @:ing someone
> [!Note]
> If you want a specific person to look at the code use the ```@``` sign and then their name.

## Task list 
- [ ] Checked the code structure so it follows guide lines
- [ ] Checked that all the points in the Issue are solved
- [ ] Checked that all the old tests still got approved

## Added tests
- [ ] Yes, I have added tests
- [ ] No, I have not added tests
- [ ] No, I need help with adding tests

2023-09-19 12:17 UTC, GabrielAdward commented
If you change to an invalid URL then this will appear 
![image](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/98411685/9d354433-7343-4193-b368-0a6ab223e539)

2023-09-21 13:28 UTC, HeWhoThreadsLightly reviewed
Looks good, test pass on my local machine.

I would like a new test that checks that user data cant be read after logging out, but we dont have time for it before friday.

2023-09-21 13:57 UTC, HeWhoThreadsLightly commented
I would like a test that:
 1 logs in
 2 tries to reed some private user data and checks that it was read succsessfully
 2 logs out
 3 tries to read the same private user data and checkt that it fails to read

2023-09-29 11:22 UTC, HeWhoThreadsLightly commented
Strange that the automatic tests have't activated.

2023-09-29 11:28 UTC, HeWhoThreadsLightly requested changes

2023-09-29 11:28 UTC, HeWhoThreadsLightly commented on src/test/logout.test.tsx
> +test("Login, check data, logout and check if information is gone", async () => {
Test looks good.

However you need to merge in the canges from main into your branch and solv the merge conflicts.
checkout main
pull
checkout successfull_logout
git merge main (or use tortoise git to merge)
fix merge conflicts (files with mexed content from both branches)
git push

2023-09-30 15:14 UTC, merged