157 design content pages
AlexTelon/FlexiCharge-My-pages pull request #166
Opened 2023-10-02 09:37 UTC by flrn579

# Pull Request
## Issue number
#157

## @:ing someone
> [!Note]
> If you want a specific person to look at the code use the ```@``` sign and then their name.

## Task list 
- [ ] Checked the code structure so it follows guide lines
- [ ] Checked that all the points in the Issue are solved
- [ ] Checked that all the old tests still got approved

## Added tests
- [ ] Yes, I have added tests
- [ ] No, I have not added tests
- [ ] No, I need help with adding tests

2023-10-02 14:48 UTC, GabrielAdward approved these changes
LGTM!

2023-10-03 08:34 UTC, HeWhoThreadsLightly requested changes
Code changes look sensible to me.

- [ ] Changes from development needs to be merged in before a PR can be completed.

- [ ] The logout test throws a error but passes i think somthing is wrong with the test. However look over the error yourself to.

`● Console

    console.error
      Error: Not implemented: navigation (except hash changes)
          at module.exports (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at navigateFetch (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
          at exports.navigate (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
          at LocationImpl._locationObjectNavigate (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:31:5)
          at LocationImpl._locationObjectSetterNavigate (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:25:17)
          at LocationImpl.set href [as href] (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:47:10)
          at Location.set href [as href] (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/node_modules/jsdom/lib/jsdom/living/generated/Location.js:121:37)
          at AuthService.logout (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/components/AuthService.tsx:109:5)
          at _callee$ (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:14:17)
          at tryCatch (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:[11](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6381607004/job/17318403416?pr=166#step:5:12):2404)
          at Generator._invoke (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:11:1964)
          at Generator.next (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:11:3255)
          at asyncGeneratorStep (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:13:103)
          at _next (/home/runner/work/FlexiCharge-My-pages/FlexiCharge-My-pages/src/test/logout.test.tsx:15:194)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) undefined

      107 |   logout() {
      108 |     localStorage.removeItem("user");
    > 109 |     window.location.href = '/sign-in';
          |     ^
      110 |   }
      111 |
      1[12](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6381607004/job/17318403416?pr=166#step:5:13) |   register(username: string, password: string, confirmPassword: string) {

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
      at navigateFetch (node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
      at exports.navigate (node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
      at LocationImpl._locationObjectNavigate (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:31:5)
      at LocationImpl._locationObjectSetterNavigate (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:25:17)
      at LocationImpl.set href [as href] (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:47:10)
      at Location.set href [as href] (node_modules/jsdom/lib/jsdom/living/generated/Location.js:121:37)
      at AuthService.logout (src/components/AuthService.tsx:109:5)
      at _callee$ (src/test/logout.test.tsx:14:17)
      at tryCatch (src/test/logout.test.tsx:11:2404)
      at Generator._invoke (src/test/logout.test.tsx:11:1964)
      at Generator.next (src/test/logout.test.tsx:11:3255)
      at asyncGeneratorStep (src/test/logout.test.tsx:[13](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6381607004/job/17318403416?pr=166#step:5:14):103)
      at _next (src/test/logout.test.tsx:[15](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6381607004/job/17318403416?pr=166#step:5:16):[19](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6381607004/job/17318403416?pr=166#step:5:20)4)`

2023-10-03 08:42 UTC, HeWhoThreadsLightly commented
Manual test results.

Page lodes localy without problems.

However

- [ ]  Signout button does not work on any of the pages.
- [ ] Navigating to profile -> update profile -> cancel takes you back to invoices tab instead of staying on the profile tab as expected.

After fixing signout 
- [ ] Uppdate the signout test so it tests the moved signout button.

2023-10-03 12:37 UTC, Nvcxlx commented
I have solved the sign-out problem, the test should also work, but I have no idea how to test it. 

The problem with the different tabs is a bigger one. All three tabs are on the same page "/profile". After the modal is closed, this page is opened, but the tab "Invoices" is the "main tab", so it is opened and not the profile tab. I think this problem should be dealt with in a new issue.

2023-10-03 20:16 UTC, HeWhoThreadsLightly commented on src/components/Tabs.tsx
> +          Sign Out
I tested the logut button manuly and it works.

However the test is still throwning;

          at processTicksAndRejections (node:internal/process/task_queues:96:5) undefined

      107 |   logout() {
      108 |     localStorage.removeItem("user");
    > 109 |     window.location.href = '/sign-in';
          |                         ^
      110 |   }
      111 |
      112 |   register(username: string, password: string, confirmPassword: string) {

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:[29](https://github.com/AlexTelon/FlexiCharge-My-pages/actions/runs/6393832327/job/17353880185?pr=166#step:5:30):45)

The offending line was added recently but not in your issue to redirect the user to the '/sign-in' page. 
The test failes becuse the simplified web browser used in `npm test` does not have a `window.location.href` to set.

We have two redirects to sign in in our current code one in src/components/Tabs.tsx and the other in src/components/AuthService.tsx
I tried removing the redirect in AuthService.tsx and it fixes the test.

The moved sign out button still logs the user out but does not redirect the user to the '/sign-in' page. 
I dont think the `<Link to="/sign-in"` part of the button works currently.

- [ ] Remove page redirect from logout() in AuthService.tsx
- [ ] Fix redirect in Sign out button

It could be a new issue if it is very complicated but i would prefer if you could take a look at it first.

2023-10-04 08:31 UTC, Nvcxlx commented on src/components/Tabs.tsx
> +          Sign Out
I'm not sure what you mean by the redirection. When I click on the sign-out button, it takes me to the sign-in page.

2023-10-04 16:10 UTC, HeWhoThreadsLightly commented on src/components/Tabs.tsx
> +          Sign Out
Your changes have fixed the problem and your code looks good.

2023-10-05 10:19 UTC, merged