142 integrate get http18202253308080authuser information
AlexTelon/FlexiCharge-My-pages pull request #168
Opened 2023-10-03 12:57 UTC by Kebiez

#142 Intergrate Get-request

@HeWhoThreadsLightly 
@GabrielAdward 

## Task list 
- [ ] Checked the code structure so it follows guide lines
- [x] Checked that all the points in the Issue are solved
- [x] Checked that all the old tests still got approved

## Added tests
- [x] Yes, I have added tests
- [ ] No, I have not added tests
- [ ] No, I need help with adding tests

2023-10-03 20:26 UTC, HeWhoThreadsLightly approved these changes

2023-10-03 20:26 UTC, HeWhoThreadsLightly commented on src/test/link.test.tsx
> +    console.log(userData)
Please remove the console.log from the test.
The logout test still throws an error message but that is not your problem.

The profile page user information looks blank to me but that is probebly because of there being no data in the backend to display for my user. (It looked like it worked on your machine)

The update profile dident work but i think that is a uppcomming issue for later.
 
 Looks good to me other than the console.log

2023-10-03 23:52 UTC, GabrielAdward commented on src/test/link.test.tsx
> +    console.log(userData)
LGTM, as Victor mentioned remove line 36

2023-10-03 23:53 UTC, GabrielAdward requested changes
LGTM, as Victor mentioned remove line 36

2023-10-04 10:33 UTC, GabrielAdward approved these changes
LGTM!

2023-10-04 10:36 UTC, merged